import React from 'react';
import { TaxExemptionReceipt, formatIndianCurrency, formatRelativeTime } from '@caretrace/shared';
import {
  FileCheck2,
  Printer,
  X,
  ShieldCheck,
  Building,
  UserCheck,
  Hash,
  Calendar,
  AlertTriangle,
  QrCode,
  CheckCircle2
} from 'lucide-react';

interface TaxExemptionReceiptModalProps {
  receipt: TaxExemptionReceipt;
  onClose: () => void;
}

export const TaxExemptionReceiptModal: React.FC<TaxExemptionReceiptModalProps> = ({
  receipt,
  onClose
}) => {
  const handlePrint = () => {
    window.print();
  };

  const formattedAmount = formatIndianCurrency(receipt.amountInr);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-fade-in print:p-0 print:bg-white">
      <div className="bg-white rounded-3xl max-w-2xl w-full p-6 sm:p-8 shadow-2xl border border-slate-300 relative overflow-hidden max-h-[95vh] overflow-y-auto print:max-h-none print:shadow-none print:border-none">
        
        {/* Prominent Demo Watermark & Badge */}
        <div className="bg-amber-500/15 border-2 border-dashed border-amber-500 rounded-2xl p-2.5 mb-5 text-center">
          <span className="text-xs sm:text-sm font-extrabold uppercase tracking-widest text-amber-900 flex items-center justify-center space-x-2">
            <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
            <span>DEMO / SAMPLE DOCUMENT — NOT A LEGAL TAX RECEIPT UNDER SEC 80G</span>
          </span>
          <p className="text-[10px] text-amber-800 mt-0.5">
            Generated by CareTrace Prototype platform for project review and simulation of Section 80G compliance.
          </p>
        </div>

        {/* Certificate Outer Border for Official Look */}
        <div className="border-4 border-double border-teal-900/40 rounded-2xl p-5 sm:p-7 relative bg-slate-50/40">
          {/* Header */}
          <div className="flex flex-col sm:flex-row items-center justify-between pb-5 border-b-2 border-teal-900/30 gap-4">
            <div className="flex items-center space-x-3 text-center sm:text-left">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-teal-800 to-slate-900 text-white flex items-center justify-center shadow-md shrink-0">
                <FileCheck2 className="w-6 h-6 text-teal-200" />
              </div>
              <div>
                <span className="text-[10px] uppercase font-bold tracking-widest text-teal-800 bg-teal-100/70 px-2 py-0.5 rounded border border-teal-300">
                  Form 10BE • Section 80G Sample Receipt
                </span>
                <h2 className="text-lg sm:text-xl font-black text-slate-900 tracking-tight mt-0.5">
                  DONATION CONTRIBUTION RECEIPT
                </h2>
                <p className="text-[11px] text-slate-500 font-mono">
                  CareTrace Cryptographic Verification Network
                </p>
              </div>
            </div>

            <div className="text-center sm:text-right shrink-0">
              <span className="text-[10px] uppercase font-bold text-slate-500 block">Receipt No.</span>
              <span className="font-mono text-xs sm:text-sm font-black text-teal-950 bg-teal-50 px-2.5 py-1 rounded border border-teal-200 block">
                {receipt.receiptNumber}
              </span>
              <span className="text-[10px] text-slate-500 block mt-1">
                Date: {new Date(receipt.date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })} ({formatRelativeTime(receipt.date)})
              </span>
            </div>
          </div>

          {/* Institution (Donee) Details */}
          <div className="mt-5 p-4 rounded-xl bg-white border border-slate-200 shadow-sm">
            <div className="flex items-center justify-between border-b border-slate-100 pb-2">
              <span className="text-[10px] uppercase font-bold text-teal-800 tracking-wider flex items-center space-x-1">
                <Building className="w-3.5 h-3.5" />
                <span>Recipient Institution (Accredited Sanctuary)</span>
              </span>
              <span className="text-[10px] text-emerald-700 font-semibold bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                Verified Child Sanctuary
              </span>
            </div>
            
            <div className="mt-2 grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              <div>
                <span className="text-[10px] text-slate-500 block">Organization Name</span>
                <p className="font-bold text-slate-900 text-sm">{receipt.institutionName}</p>
                <p className="text-[11px] text-slate-600 mt-0.5">{receipt.institutionAddress}</p>
              </div>
              <div className="space-y-1 sm:text-right">
                <div>
                  <span className="text-[10px] text-slate-500">Govt. Registration / License No:</span>
                  <p className="font-mono font-bold text-slate-800 text-xs">{receipt.institutionRegistrationNumber}</p>
                </div>
                <div>
                  <span className="text-[10px] text-slate-500">Tax Exemption PAN / 12AA Reg:</span>
                  <p className="font-mono font-bold text-slate-800 text-xs">{receipt.institutionTaxId}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Donor Information */}
          <div className="mt-4 p-4 rounded-xl bg-white border border-slate-200 shadow-sm">
            <div className="flex items-center justify-between border-b border-slate-100 pb-2">
              <span className="text-[10px] uppercase font-bold text-teal-800 tracking-wider flex items-center space-x-1">
                <UserCheck className="w-3.5 h-3.5" />
                <span>Donor Particulars</span>
              </span>
              <span className="text-[10px] font-mono text-slate-500">Consignment Ref: {receipt.donationId}</span>
            </div>

            <div className="mt-2 grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
              <div>
                <span className="text-[10px] text-slate-500 block">Donor Full Name</span>
                <p className="font-bold text-slate-900">{receipt.donorName}</p>
              </div>
              <div>
                <span className="text-[10px] text-slate-500 block">Email Address</span>
                <p className="font-mono text-slate-700 text-[11px]">{receipt.donorEmail}</p>
              </div>
              <div>
                <span className="text-[10px] text-slate-500 block">Contact Phone</span>
                <p className="font-mono text-slate-700 text-[11px]">{receipt.donorPhone || '+91 98401 23456'}</p>
              </div>
            </div>
          </div>

          {/* Contribution Amount Breakdown */}
          <div className="mt-4 p-4 rounded-xl bg-gradient-to-br from-teal-900 to-slate-900 text-white shadow-md">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-teal-700/60 pb-3">
              <div>
                <span className="text-teal-300 text-[10px] uppercase tracking-wider font-bold block">
                  Donation Value (Indian Rupees)
                </span>
                <span className="text-2xl sm:text-3xl font-black font-mono tracking-tight text-white mt-0.5 block">
                  {formattedAmount}
                </span>
              </div>
              <div className="sm:text-right">
                <span className="text-[10px] text-teal-300 block">Payment Instrument</span>
                <span className="font-mono text-xs font-semibold text-emerald-300">
                  {receipt.paymentMethod}
                </span>
                <p className="text-[10px] font-mono text-teal-200/80 mt-0.5">
                  Ref: {receipt.upiTransactionId}
                </p>
              </div>
            </div>

            <div className="mt-3">
              <span className="text-[10px] uppercase font-bold text-teal-300 tracking-wider block">
                Amount in Words (Indian Numbering Convention)
              </span>
              <p className="text-xs sm:text-sm font-semibold text-teal-100 italic mt-0.5">
                "{receipt.amountInWords}"
              </p>
            </div>
          </div>

          {/* Cryptographic Proof & Ledger Stamp */}
          <div className="mt-4 p-3.5 rounded-xl bg-white border border-slate-200 shadow-sm text-xs space-y-2">
            <div className="flex items-center justify-between text-slate-700 font-bold border-b border-slate-100 pb-2">
              <span className="flex items-center space-x-1 text-teal-900">
                <Hash className="w-4 h-4 text-teal-700" />
                <span>Cryptographic SHA-256 Ledger Seal</span>
              </span>
              <span className="text-[10px] font-mono text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200 flex items-center space-x-1">
                <CheckCircle2 className="w-3 h-3" />
                <span>Mined at Block #{receipt.ledgerBlockIndex}</span>
              </span>
            </div>

            <div className="font-mono text-[11px] bg-slate-50 p-2.5 rounded-lg border border-slate-200 break-all text-slate-700">
              <span className="text-[9px] uppercase font-sans font-bold text-slate-400 block mb-0.5">SHA-256 Block Hash</span>
              {receipt.ledgerBlockHash}
            </div>

            <div className="flex items-center justify-between text-[11px] text-slate-500 pt-1">
              <span>Event: <strong className="text-slate-800">MONETARY_DONATION_CONFIRMED</strong></span>
              <span>Requirement: <strong className="text-slate-800 truncate max-w-[200px]">{receipt.requirementTitle}</strong></span>
            </div>
          </div>

          {/* Footer Sign-off */}
          <div className="mt-6 pt-4 border-t border-slate-200 flex flex-col sm:flex-row items-center justify-between text-[11px] text-slate-500 gap-3">
            <p className="text-center sm:text-left italic">
              Electronically generated by CareTrace Open Verification Protocol. Valid without physical signature.
            </p>
            <div className="text-center sm:text-right shrink-0">
              <span className="font-semibold text-slate-800 block">CareTrace Compliance Gateway</span>
              <span className="text-[10px] text-slate-400">Zero-Trust Donation Verification</span>
            </div>
          </div>
        </div>

        {/* Action Buttons (Hidden on Print) */}
        <div className="mt-6 flex items-center justify-between print:hidden">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-100 rounded-xl"
          >
            Close
          </button>

          <div className="flex items-center space-x-2">
            <button
              type="button"
              onClick={handlePrint}
              className="px-4 py-2 text-xs font-semibold bg-slate-900 hover:bg-black text-white rounded-xl shadow-sm flex items-center space-x-1.5 transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / Save PDF</span>
            </button>
            <button
              type="button"
              onClick={onClose}
              className="px-5 py-2 text-xs font-semibold bg-teal-700 hover:bg-teal-800 text-white rounded-xl shadow-md transition-colors"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

