import React from 'react';
import { TaxExemptionReceipt, formatIndianCurrency, formatRelativeTime } from '@caretrace/shared';
import {
  FileCheck2,
  Printer,
  X,
  ShieldCheck,
  Building,
  UserCheck,
  Hash,
  Calendar,
  AlertTriangle,
  QrCode,
  CheckCircle2
} from 'lucide-react';

interface TaxExemptionReceiptModalProps {
  receipt: TaxExemptionReceipt;
  onClose: () => void;
}

export const TaxExemptionReceiptModal: React.FC<TaxExemptionReceiptModalProps> = ({
  receipt,
  onClose
}) => {
  const handlePrint = () => {
    window.print();
  };

  const formattedAmount = formatIndianCurrency(receipt.amountInr);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-md animate-fade-in print:p-0 print:bg-white">
      <div className="bg-surface-card rounded-3xl max-w-2xl w-full p-6 sm:p-8 shadow-elevated border border-surface-border relative overflow-hidden max-h-[95vh] overflow-y-auto animate-slide-up card-premium print:max-h-none print:shadow-none print:border-none">
        
        {/* Prominent Demo Watermark & Badge */}
        <div className="bg-amber-50/80 border-2 border-dashed border-amber-500/50 rounded-2xl p-3 mb-6 text-center shadow-sm">
          <span className="text-xs sm:text-sm font-sans font-black uppercase tracking-widest text-amber-900 flex items-center justify-center space-x-2">
            <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
            <span>DEMO / SAMPLE DOCUMENT — NOT A LEGAL TAX RECEIPT UNDER SEC 80G</span>
          </span>
          <p className="text-[10px] font-sans font-medium text-amber-800 mt-1">
            Generated by CareTrace Prototype platform for project review and simulation of Section 80G compliance.
          </p>
        </div>

        {/* Certificate Outer Border for Official Look */}
        <div className="border-4 border-double border-teal-900/30 rounded-2xl p-5 sm:p-7 relative bg-slate-50/30 shadow-inner">
          {/* Header */}
          <div className="flex flex-col sm:flex-row items-center justify-between pb-6 border-b-2 border-teal-900/20 gap-4">
            <div className="flex items-center space-x-4 text-center sm:text-left">
              <div className="w-14 h-14 rounded-2xl gradient-primary text-white flex items-center justify-center shadow-glow-teal shrink-0">
                <FileCheck2 className="w-7 h-7 text-teal-100" />
              </div>
              <div>
                <span className="text-[10px] uppercase font-sans font-bold tracking-widest text-teal-900 bg-teal-50 px-2.5 py-0.5 rounded-full border border-teal-200 shadow-sm">
                  Form 10BE • Section 80G Sample Receipt
                </span>
                <h2 className="text-xl sm:text-3xl font-display font-bold text-slate-900 tracking-tight mt-1.5">
                  DONATION RECEIPT
                </h2>
                <p className="text-xs text-slate-500 font-mono font-medium mt-0.5">
                  CareTrace Cryptographic Verification Network
                </p>
              </div>
            </div>

            <div className="text-center sm:text-right shrink-0">
              <span className="text-[10px] uppercase font-sans font-bold tracking-wider text-slate-500 block mb-1">Receipt No.</span>
              <span className="font-mono text-sm sm:text-base font-black text-teal-950 bg-surface-canvas px-3 py-1.5 rounded-xl border border-surface-border block shadow-inner">
                {receipt.receiptNumber}
              </span>
              <span className="text-[10px] text-slate-500 font-medium block mt-1.5">
                Date: {new Date(receipt.date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })} ({formatRelativeTime(receipt.date)})
              </span>
            </div>
          </div>

          {/* Institution (Donee) Details */}
          <div className="mt-6 p-4.5 rounded-xl bg-surface-card border border-surface-border shadow-sm">
            <div className="flex items-center justify-between border-b border-surface-border pb-3">
              <span className="text-[10px] uppercase font-sans font-bold text-teal-800 tracking-wider flex items-center space-x-1.5">
                <Building className="w-3.5 h-3.5" />
                <span>Recipient Institution (Accredited Sanctuary)</span>
              </span>
              <span className="text-[10px] font-sans font-bold text-emerald-800 bg-emerald-50 px-2.5 py-0.5 rounded-full border border-emerald-200 shadow-sm">
                Verified Child Sanctuary
              </span>
            </div>
            
            <div className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
              <div>
                <span className="text-[10px] uppercase font-bold tracking-wider text-slate-500 block mb-0.5">Organization Name</span>
                <p className="font-sans font-bold text-slate-900 text-sm">{receipt.institutionName}</p>
                <p className="text-[11px] font-sans text-slate-600 mt-1">{receipt.institutionAddress}</p>
              </div>
              <div className="space-y-2 sm:text-right">
                <div>
                  <span className="text-[10px] uppercase font-bold tracking-wider text-slate-500 block mb-0.5">Govt. Registration / License No:</span>
                  <p className="font-mono font-bold text-slate-800 text-xs">{receipt.institutionRegistrationNumber}</p>
                </div>
                <div>
                  <span className="text-[10px] uppercase font-bold tracking-wider text-slate-500 block mb-0.5">Tax Exemption PAN / 12AA Reg:</span>
                  <p className="font-mono font-bold text-slate-800 text-xs">{receipt.institutionTaxId}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Donor Information */}
          <div className="mt-4 p-4.5 rounded-xl bg-surface-card border border-surface-border shadow-sm">
            <div className="flex items-center justify-between border-b border-surface-border pb-3">
              <span className="text-[10px] uppercase font-sans font-bold text-teal-800 tracking-wider flex items-center space-x-1.5">
                <UserCheck className="w-3.5 h-3.5" />
                <span>Donor Particulars</span>
              </span>
              <span className="text-[10px] font-mono font-medium text-slate-500">Consignment Ref: {receipt.donationId}</span>
            </div>

            <div className="mt-3 grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
              <div>
                <span className="text-[10px] uppercase font-bold tracking-wider text-slate-500 block mb-0.5">Donor Full Name</span>
                <p className="font-sans font-bold text-slate-900 text-sm">{receipt.donorName}</p>
              </div>
              <div>
                <span className="text-[10px] uppercase font-bold tracking-wider text-slate-500 block mb-0.5">Email Address</span>
                <p className="font-mono text-slate-700 text-xs">{receipt.donorEmail}</p>
              </div>
              <div>
                <span className="text-[10px] uppercase font-bold tracking-wider text-slate-500 block mb-0.5">Contact Phone</span>
                <p className="font-mono text-slate-700 text-xs">{receipt.donorPhone || '+91 98401 23456'}</p>
              </div>
            </div>
          </div>

          {/* Contribution Amount Breakdown */}
          <div className="mt-5 p-5 rounded-xl bg-gradient-to-br from-teal-900 to-slate-900 text-white shadow-card">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-teal-700/60 pb-4">
              <div>
                <span className="text-teal-300 text-[10px] uppercase tracking-widest font-sans font-bold block mb-1">
                  Donation Value (Indian Rupees)
                </span>
                <span className="text-3xl sm:text-4xl font-black font-mono tracking-tight text-white mt-0.5 block">
                  {formattedAmount}
                </span>
              </div>
              <div className="sm:text-right">
                <span className="text-[10px] text-teal-300 uppercase tracking-widest font-sans font-bold block mb-1">Payment Instrument</span>
                <span className="font-mono text-sm font-bold text-emerald-300 bg-black/20 px-2.5 py-1 rounded-lg border border-white/10">
                  {receipt.paymentMethod}
                </span>
                <p className="text-[10px] font-mono font-medium text-teal-200/80 mt-2">
                  Ref: {receipt.upiTransactionId}
                </p>
              </div>
            </div>

            <div className="mt-4">
              <span className="text-[10px] uppercase font-sans font-bold text-teal-300 tracking-widest block mb-1">
                Amount in Words (Indian Numbering Convention)
              </span>
              <p className="text-sm sm:text-base font-display text-teal-50 italic">
                "{receipt.amountInWords}"
              </p>
            </div>
          </div>

          {/* Cryptographic Proof & Ledger Stamp */}
          <div className="mt-5 p-4.5 rounded-xl bg-surface-card border border-surface-border shadow-sm text-xs space-y-3">
            <div className="flex items-center justify-between text-slate-700 font-sans font-bold border-b border-surface-border pb-3">
              <span className="flex items-center space-x-1.5 text-teal-900">
                <Hash className="w-4 h-4 text-teal-700" />
                <span>Cryptographic SHA-256 Ledger Seal</span>
              </span>
              <span className="text-[10px] font-mono font-bold text-emerald-800 bg-emerald-50 px-2.5 py-0.5 rounded-full border border-emerald-200 flex items-center space-x-1 shadow-sm">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                <span>Mined at Block #{receipt.ledgerBlockIndex}</span>
              </span>
            </div>

            <div className="font-mono text-xs bg-surface-canvas p-3 rounded-xl border border-surface-border break-all text-slate-800 shadow-inner">
              <span className="text-[10px] uppercase font-sans font-bold tracking-wider text-slate-500 block mb-1">SHA-256 Block Hash</span>
              {receipt.ledgerBlockHash}
            </div>

            <div className="flex items-center justify-between text-xs font-sans text-slate-600 pt-1">
              <span>Event: <strong className="text-slate-900 bg-slate-100 px-1.5 py-0.5 rounded font-mono text-[10px]">MONETARY_DONATION_CONFIRMED</strong></span>
              <span>Requirement: <strong className="text-slate-900 font-bold truncate max-w-[200px]">{receipt.requirementTitle}</strong></span>
            </div>
          </div>

          {/* Footer Sign-off */}
          <div className="mt-7 pt-5 border-t border-teal-900/20 flex flex-col sm:flex-row items-center justify-between text-[11px] font-sans text-slate-500 gap-4">
            <p className="text-center sm:text-left italic font-medium">
              Electronically generated by CareTrace Open Verification Protocol. Valid without physical signature.
            </p>
            <div className="text-center sm:text-right shrink-0">
              <span className="font-bold text-slate-800 block">CareTrace Compliance Gateway</span>
              <span className="text-[10px] text-slate-500 font-medium">Zero-Trust Donation Verification</span>
            </div>
          </div>
        </div>

        {/* Action Buttons (Hidden on Print) */}
        <div className="mt-7 flex items-center justify-between print:hidden">
          <button
            type="button"
            onClick={onClose}
            className="px-5 py-2.5 text-xs font-sans font-bold text-slate-600 hover:text-slate-800 hover:bg-surface-subtle rounded-xl transition-colors press-effect"
          >
            Close
          </button>

          <div className="flex items-center space-x-3">
            <button
              type="button"
              onClick={handlePrint}
              className="px-5 py-2.5 text-xs font-sans font-bold bg-surface-card hover:bg-surface-subtle border border-surface-border text-slate-700 rounded-xl shadow-sm flex items-center space-x-2 transition-colors press-effect hover-lift"
            >
              <Printer className="w-4 h-4" />
              <span>Print / Save PDF</span>
            </button>
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-2.5 text-xs font-sans font-bold gradient-primary text-white rounded-xl shadow-glow-teal hover-lift transition-all press-effect"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

